// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbybzxwvggqtvxdfwerg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieWJ6eHd2Z2dxdHZ4ZGZ3ZXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMjE5OTMsImV4cCI6MjA1MTg5Nzk5M30.gHu8n31VtuC5inCbxOJ-OZStH0R5qiO8iy05N_1DOik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);